name: student_den
description: "Student Den - Thesis Project By Mariam Ustiashvili"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  flutter_bloc: ^8.1.6
  easy_localization: ^3.0.0
  equatable: ^2.0.7
  shared_preferences: ^2.2.2
  connectivity_plus: ^3.0.0
  responsive_grid_list: ^1.4.0
  path_provider: ^2.1.2
  # Firebase dependencies (latest as of April 2025)
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_crashlytics: ^4.3.5

  # UI + base packages
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - lib/database/posts_data.json
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterLight.ttf
          weight: 300
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700